// Package scheme provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package scheme

import (
	"time"
)

// Defines values for Status.
const (
	Ok        Status = "ok"
	Unhealthy Status = "unhealthy"
)

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	// Title The title/description of the todo
	Title string `json:"title"`
}

// Error defines model for Error.
type Error struct {
	// Code A unique error code for programmatic handling
	Code int `json:"code"`

	// Message A human-readable error message
	Message string `json:"message"`
}

// Status The health status of the service
type Status string

// Todo defines model for Todo.
type Todo struct {
	// Completed Whether the todo is completed
	Completed bool `json:"completed"`

	// CreatedAt When the todo was created
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier for the todo
	Id string `json:"id"`

	// Title The title/description of the todo
	Title string `json:"title"`
}

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest
