// Package scheme provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package scheme

// Defines values for Status.
const (
	Ok        Status = "ok"
	Unhealthy Status = "unhealthy"
)

// Error defines model for Error.
type Error struct {
	// Code A unique error code for programmatic handling
	Code int `json:"code"`

	// Message A human-readable error message
	Message string `json:"message"`
}

// Status The health status of the service
type Status string
