openapi: 3.0.0
info:
  title: Todo Application API
  version: 1.0.0
  description: Basic todo application

paths:
  /health:
    get:
      summary: Health Check
      operationId: getHealth
      tags:
        - Health
      responses:
        200:
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
                required:
                  - status
        
        500:
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Status:
      type: string
      enum:
        - ok
        - unhealthy
      description: The health status of the service
      example: ok
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: A unique error code for programmatic handling
          example: 500
        message:
          type: string
          description: A human-readable error message
          example: "An unexpected error occurred on the server."